### ISSUE TITLE
Monitor Enrollment Program Tokens

### ISSUE THREAD

**Issue by JF-JX** [CLiX-1/cmk_plugin_ms_intune#1]
Hey there,
It would be awesome if you could extend the MKP so that one can monitor the expiry date of the Program Enrollment Tokens.
Microsoft Docs: https://learn.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios
Graph API Endpoint should be: https://learn.microsoft.com/en-us/graph/api/resources/intune-enrollment-deponboardingsetting?view=graph-rest-beta
It is very important to renew these enrollment tokens in time, since you won't be able to synchronize new devices from Apple Business Manager into Intune anymore if the token is expired.

**Comment by CLiX-1** [comment]
Thank you for your feedback.
I've uploaded v1.2.0 with a new check "Intune Apple ADE Tokens" to monitor the expiration time of the "Automated Device Enrollment" tokens from the Intune "Enrollment Program Tokens" section.

**Comment by JF-JX** [comment]
Thanks for your work, great stuff! This really helps me out a lot.
If you find the time it would be nice if you upload the new MKP to the checkmk exchange :)

**Comment by CLiX-1** [comment]
I've uploaded the MKP to Checkmk exchange yesterday.
The status is "Version is under review".
